package GUI;

import Database.DB;
import Model.Save;
import Model.Validation;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import static javax.swing.BorderFactory.createTitledBorder;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;

public class AddCustomer extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    private Main menu;
    private Customers cus;

    public AddCustomer() {
        initComponents();
        generateCustomerID();

    }

    public AddCustomer(Main m, Customers c, boolean b) {
        this();
        this.menu = m;
        this.cus = c;
        menu.setEnabled(false);
        if (b) {
            jLabel5.setVisible(false);
            active.setVisible(false);
            inactive.setVisible(false);
        } else {
            jLabel2.setText("Customer");
            jLabel5.setVisible(true);
            active.setVisible(true);
            inactive.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        state = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        txt_nic = new javax.swing.JTextField();
        txt_company = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_street = new javax.swing.JTextField();
        txt_mobile = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        id_customer = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        active = new javax.swing.JRadioButton();
        inactive = new javax.swing.JRadioButton();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(225, 225, 225));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fname.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_fname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "First Name", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_fname.setOpaque(false);
        txt_fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fnameFocusLost(evt);
            }
        });
        jPanel1.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 250, 50));

        txt_lname.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_lname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Last Name", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_lname.setOpaque(false);
        txt_lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lnameFocusLost(evt);
            }
        });
        jPanel1.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 25, 250, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Gender");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 50, 20));

        male.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(male);
        male.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        male.setText("Male");
        male.setBorder(null);
        male.setContentAreaFilled(false);
        male.setFocusPainted(false);
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 115, -1, -1));

        female.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(female);
        female.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        female.setText("Female");
        female.setBorder(null);
        female.setContentAreaFilled(false);
        female.setFocusPainted(false);
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 115, -1, -1));

        txt_nic.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_nic.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "N I C", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_nic.setOpaque(false);
        txt_nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nicFocusLost(evt);
            }
        });
        txt_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nicKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 50));

        txt_company.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_company.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Company", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_company.setOpaque(false);
        txt_company.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_companyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_companyFocusLost(evt);
            }
        });
        jPanel1.add(txt_company, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 175, 530, 50));

        txt_email.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "E mail", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_email.setOpaque(false);
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 50));

        txt_street.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_street.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Street", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_street.setOpaque(false);
        txt_street.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_streetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_streetFocusLost(evt);
            }
        });
        jPanel1.add(txt_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 325, 250, 50));

        txt_mobile.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_mobile.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Phone No", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_mobile.setOpaque(false);
        txt_mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mobileFocusLost(evt);
            }
        });
        txt_mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mobileKeyTyped(evt);
            }
        });
        jPanel1.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 250, 50));

        txt_city.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_city.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "City", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_city.setOpaque(false);
        txt_city.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cityFocusLost(evt);
            }
        });
        jPanel1.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 325, 250, 50));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 580, 421));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_customer.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        id_customer.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Customer ID", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel3.add(id_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 50));

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear1.png"))); // NOI18N
        btn_clear.setBorder(null);
        btn_clear.setBorderPainted(false);
        btn_clear.setContentAreaFilled(false);
        btn_clear.setFocusPainted(false);
        btn_clear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear2.png"))); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 40));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save1.png"))); // NOI18N
        btn_save.setBorder(null);
        btn_save.setBorderPainted(false);
        btn_save.setContentAreaFilled(false);
        btn_save.setFocusPainted(false);
        btn_save.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save2.png"))); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel3.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Status");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, 20));

        active.setBackground(new java.awt.Color(255, 255, 255));
        state.add(active);
        active.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        active.setSelected(true);
        active.setText("   Active");
        active.setBorder(null);
        active.setContentAreaFilled(false);
        active.setFocusPainted(false);
        jPanel3.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, -1));

        inactive.setBackground(new java.awt.Color(255, 255, 255));
        state.add(inactive);
        inactive.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        inactive.setText("   Inactive");
        inactive.setBorder(null);
        inactive.setContentAreaFilled(false);
        inactive.setFocusPainted(false);
        jPanel3.add(inactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 190, 421));

        header.setBackground(new java.awt.Color(253, 253, 253));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(117, 113, 112));
        jLabel2.setText("Add Customer");
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit1.png"))); // NOI18N
        btn_Exit.setBorder(null);
        btn_Exit.setBorderPainted(false);
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setFocusPainted(false);
        btn_Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit2.png"))); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        header.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 0, 25, 25));

        jPanel4.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 797, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        cus.loadTableData();
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void txt_fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusGained
        txt_fname.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "First Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_fnameFocusGained

    private void txt_fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusLost
        txt_fname.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "First Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_fnameFocusLost

    private void txt_lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusGained
        txt_lname.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Last Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_lnameFocusGained

    private void txt_lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusLost
        txt_lname.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Last Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_lnameFocusLost

    private void txt_nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nicFocusGained
        txt_nic.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "N I C", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_nicFocusGained

    private void txt_nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nicFocusLost
        txt_nic.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "N I C", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_nicFocusLost

    private void txt_companyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_companyFocusGained
        txt_company.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Company", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_companyFocusGained

    private void txt_companyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_companyFocusLost
        txt_company.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Company", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_companyFocusLost

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        txt_email.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "E mail", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        txt_email.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "E mail", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mobileFocusGained
        txt_mobile.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Phone No", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_mobileFocusGained

    private void txt_mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mobileFocusLost
        txt_mobile.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Phone No", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_mobileFocusLost

    private void txt_streetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_streetFocusGained
        txt_street.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Street", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_streetFocusGained

    private void txt_streetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_streetFocusLost
        txt_street.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Street", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_streetFocusLost

    private void txt_cityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cityFocusGained
        txt_city.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "City", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_cityFocusGained

    private void txt_cityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cityFocusLost
        txt_city.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "City", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_cityFocusLost

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (txt_fname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(menu, "You must enter the customer name", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!txt_fname.getText().equals("")) {
                String gen;
                if (male.isSelected()) {
                    gen = "Male";
                } else {
                    gen = "Female";
                }
                int status;
                if (active.isSelected()) {
                    status = 1;
                } else {
                    status = 0;
                }

                try {
                    DB.iud("INSERT INTO customer VALUES('" + id_customer.getText() + "','" + txt_fname.getText() + "','" + txt_lname.getText() + "','" + gen + "',"
                            + "'" + txt_nic.getText() + "','" + txt_company.getText() + "','" + txt_email.getText() + "','" + txt_mobile.getText() + "','" + txt_street.getText() + "','" + txt_city.getText() + "','" + status + "')");
                    new Save().setVisible(true);
                    clear();
                    generateCustomerID();
                    cus.loadTableData();
                } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e) {
                    if (JOptionPane.showConfirmDialog(this, "Do you want to update this customers data", "Update Customer Data", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE) == 0) {
                        try {
                            DB.iud("UPDATE customer SET fname='" + txt_fname.getText() + "', lname='" + txt_lname.getText() + "', gender='" + gen + "',"
                                    + " nic='" + txt_nic.getText() + "', company='" + txt_company.getText() + "', street='" + txt_street.getText() + "', city='" + txt_city.getText() + "', email='" + txt_email.getText() + "', mobile='" + txt_mobile.getText() + "', state='" + status + "' WHERE id_customer='" + id_customer.getText() + "'");
                            new Save().setVisible(true);
                            clear();
                            generateCustomerID();
                            menu.setEnabled(true);
                            cus.loadTableData();
                            this.dispose();
                        } catch (Exception x) {
                            x.printStackTrace();
                        }
                    }

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Plaese Enter data", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        if (JOptionPane.showConfirmDialog(menu, "Do you want clear this data", "Clear", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
            clear();
            generateCustomerID();
        }

    }//GEN-LAST:event_btn_clearActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txt_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicKeyTyped
        Validation.setLength(evt, txt_nic.getText(), 12);
    }//GEN-LAST:event_txt_nicKeyTyped

    private void txt_mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mobileKeyTyped
        Validation.setLength(evt, txt_mobile.getText(), 12);
        Validation.setDigitsOnly(evt);
    }//GEN-LAST:event_txt_mobileKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        if (Validation.isValidemail(txt_email.getText())) {
            txt_email.setForeground(Color.BLACK);
        } else {
            txt_email.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txt_emailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton active;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JPanel header;
    private javax.swing.JLabel id_customer;
    private javax.swing.JRadioButton inactive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton male;
    private javax.swing.ButtonGroup state;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_street;
    // End of variables declaration//GEN-END:variables

    private void generateCustomerID() {
        try {
            ResultSet rs = DB.search("SELECT COUNT(id_customer) AS id FROM customer");
            if (rs.next()) {
                int rowcount = rs.getInt("id");
                rowcount++;
                id_customer.setText(String.format("%0" + 6 + "d", rowcount));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clear() {
        txt_fname.setText(null);
        txt_lname.setText(null);
        txt_nic.setText(null);
        txt_company.setText(null);
        txt_email.setText(null);
        txt_mobile.setText(null);
        txt_street.setText(null);
        txt_city.setText(null);
    }

    public void updateData(String customerID) {
        try {
            ResultSet rs = DB.search("SELECT * FROM customer WHERE id_customer = '" + customerID + "'");
            if (rs.next()) {
                id_customer.setText(rs.getString(1));
                txt_fname.setText(rs.getString(2));
                txt_lname.setText(rs.getString(3));
                if (rs.getString(4).equals("Male")) {
                    male.setSelected(true);
                } else {
                    female.setSelected(true);
                }
                txt_nic.setText(rs.getString(5));
                txt_company.setText(rs.getString(6));
                txt_email.setText(rs.getString(7));
                txt_mobile.setText(rs.getString(8));
                txt_street.setText(rs.getString(9));
                txt_city.setText(rs.getString(10));
                if (rs.getInt(11) == 1) {
                    active.setSelected(true);
                } else {
                    inactive.setSelected(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
